version: '3'
services:
    discord_bot_template:
        container_name: discord_bot_template
        hostname: discord_bot_template
        build: .
        working_dir: /root
        environment:
          TZ: Asia/Tokyo
        volumes:
          - ./src:/root/src
          - ./logs:/root/logs
        env_file:
          - .env
        entrypoint: python ./src/main.py
